let patientAgeGroup = null;
let deferredPrompt = null;
let currentLanguage = localStorage.getItem("carebridgeLanguage") || "en";
let currentView = { screen: "home" };

/* ===================== LANGUAGE ===================== */

const translations = {
  en: {
    tagline: "Offline-first symptom triage prototype",
    startCheck: "Start Symptom Check",
    about: "About CareBridge",
    install: "Install CareBridge",
    disclaimer: "⚠️ This is a prototype for guidance only, not a medical diagnosis tool. If symptoms feel severe, seek professional care.",
    footer: "Built for 3MTT NextGen Knowledge Showcase • MVP Prototype",

    patientProfile: "Patient Profile",
    whoIsThisFor: "Who is this assessment for?",
    age_child: "Child (0–12)",
    age_teen: "Teen (13–17)",
    age_adult: "Adult (18–64)",
    age_elderly: "Elderly (65+)",
    back: "⬅ Back",

    selectSymptom: "Select Symptom Category",
    assessmentFor: "Assessment for",
    changeAge: "👤 Change Age Group",
    searchPlaceholder: "🔎 Search symptoms (tooth, fever, vomiting...)",
    noResults: "No matching symptom found. Try: fever, tooth, stomach, vomiting.",
    symptom_fever: "🤒 Fever / Malaria",
    symptom_dental: "🦷 Dental Pain",
    symptom_stomach: "🤢 Stomach Pain",
    symptom_snakeBite: "🐍 Snake Bite",
    symptom_cancer: "🧬 Cancer Screening",
    cancer_title: "Cancer Screening",
    cancer_coming_soon: "Coming soon",

    snake_title: "Snake Bite Assessment",
    snake_q1: "Was the bite from a snake, or do you strongly suspect it was a snake?",
    notSure: "Not Sure",
    urgent: "🔴 Urgent",
    snake_emergency: "Snake bite is treated as an emergency. Seek medical help immediately.",
    snake_do_title: "What to do now",
    snake_do_1: "Keep the bitten area still.",
    snake_do_2: "Remove tight clothing, rings or bracelets near the bite.",
    snake_do_3: "Go to the nearest hospital immediately.",
    snake_dont_title: "Do NOT do this",
    snake_dont_1: "Do not cut the wound.",
    snake_dont_2: "Do not suck the venom.",
    snake_dont_3: "Do not apply harmful substances.",

    feverTitle: "Fever Assessment",
    feverQ1: "Is the fever very high (about 39°C or more)?",
    feverQ2Danger: "Any danger signs (severe weakness, confusion, convulsions, difficulty breathing)?",
    feverQ2Days: "Has the fever lasted more than 3 days?",

    dentalTitle: "Dental Pain Assessment",
    dentalQ1: "Is the pain severe?",
    dentalQ2: "Is there swelling on the face or gums?",

    stomachTitle: "Stomach Pain Assessment",
    stomachQ1: "Is the pain severe?",
    stomachQ2: "Are you vomiting?",

    yes: "Yes",
    no: "No",

    resultTitle: "Assessment Result",
    nextSteps: "Next steps",
    redFlags: "Red flags (go for care if any happens)",
    generatedBy: "Generated by CareBridge Prototype",

    result_urgent_title: "🔴 Urgent",
    result_urgent_action: "Seek medical help immediately.",
    result_moderate_title: "🟡 Moderate",
    result_moderate_action: "Monitor closely and consider a clinic visit soon.",
    result_mild_title: "🟢 Mild",
    result_mild_action: "Likely mild — monitor symptoms and practice self-care.",

    aboutTitle: "About CareBridge",
    aboutText1: "CareBridge is a lightweight symptom triage prototype built for low-connectivity communities. It helps users quickly check common symptoms and understand whether a situation is likely mild, moderate, or urgent.",
    aboutText2: "This is an MVP prototype for the 3MTT NextGen Knowledge Showcase. It is not a medical diagnosis tool. If symptoms feel severe or worsen, seek professional care.",

    newAssessment: "New Assessment",
    home: "Home",
    ageNotePrefix: "For"
  },

  pidgin: {
    tagline: "Offline-first body check prototype",
    startCheck: "Check Body",
    about: "About CareBridge",
    install: "Install CareBridge",
    disclaimer: "⚠️ This na prototype for guidance only, e no be medical diagnosis tool. If symptom serious, abeg find professional care.",
    footer: "Built for 3MTT NextGen Knowledge Showcase • MVP Prototype",

    patientProfile: "Patient Profile",
    whoIsThisFor: "Na who get this problem?",
    age_child: "Pikin (0–12)",
    age_teen: "Teen (13–17)",
    age_adult: "Adult (18–64)",
    age_elderly: "Old person (65+)",
    back: "⬅ Back",

    selectSymptom: "Choose Symptom",
    assessmentFor: "Assessment for",
    changeAge: "👤 Change Age Group",
    searchPlaceholder: "🔎 Search symptom (tooth, fever, vomiting...)",
    noResults: "No symptom match. Try: fever, tooth, stomach, vomiting.",
    symptom_fever: "🤒 Fever / Malaria",
    symptom_dental: "🦷 Tooth Pain",
    symptom_stomach: "🤢 Belle Pain",
    symptom_snakeBite: "🐍 Snake Bite",

    snake_title: "Snake Bite Check",
    snake_q1: "You sure say na snake bite am or you suspect say na snake?",
    notSure: "Not Sure",
    urgent: "🔴 Urgent",
    snake_emergency: "Snake bite na emergency. Abeg go hospital sharp sharp.",
    snake_do_title: "Wetin you suppose do",
    snake_do_1: "Make the place wey snake bite stay still.",
    snake_do_2: "Remove ring or tight cloth near the bite.",
    snake_do_3: "Go hospital immediately.",
    snake_dont_title: "No do this",
    snake_dont_1: "No cut the wound.",
    snake_dont_2: "No suck the venom.",
    snake_dont_3: "No put harmful substances for the wound.",

    feverTitle: "Fever Check",
    feverQ1: "Body hot too much, like 39 degree or more?",
    feverQ2Danger: "Any danger sign dey, like confusion, convulsion, body weak well-well or problem to breathe?",
    feverQ2Days: "This fever don pass 3 days?",

    dentalTitle: "Tooth Pain Check",
    dentalQ1: "The pain serious?",
    dentalQ2: "Any swelling for face or gum?",

    stomachTitle: "Belle Pain Check",
    stomachQ1: "The pain serious?",
    stomachQ2: "You dey vomit?",

    yes: "Yes",
    no: "No",

    resultTitle: "Result",
    nextSteps: "Wetin you fit do next",
    redFlags: "Danger signs",
    generatedBy: "Generated by CareBridge Prototype",

    result_urgent_title: "🔴 Urgent",
    result_urgent_action: "Go hospital sharp-sharp.",
    result_moderate_title: "🟡 Moderate",
    result_moderate_action: "Watch am well and think of clinic visit soon.",
    result_mild_title: "🟢 Mild",
    result_mild_action: "E fit be mild — rest and take care of yourself.",

    aboutTitle: "About CareBridge",
    aboutText1: "CareBridge na simple symptom triage prototype wey dem build for places wey network no strong. E help people check common symptoms fast and know if the case mild, moderate, or urgent.",
    aboutText2: "This na MVP prototype for 3MTT NextGen Knowledge Showcase. E no be medical diagnosis tool. If symptom serious or e worsen, go find professional care.",

    newAssessment: "Check Again",
    home: "Home",
    ageNotePrefix: "For"
  },

  yo: {
    tagline: "Àpẹẹrẹ ayẹwo aami aisan ti n ṣiṣẹ lai intanẹẹti",
    startCheck: "Bẹrẹ Ayẹwo Aami Aisan",
    about: "Nipa CareBridge",
    install: "Fi CareBridge sori ẹrọ",
    disclaimer: "⚠️ Eyi jẹ àpẹẹrẹ ìtọ́sọ́nà nikan, kì í ṣe irinṣẹ ìdánimọ àìsàn. Bí aami aisan bá le, wá ìtọju amọja.",
    footer: "Built for 3MTT NextGen Knowledge Showcase • MVP Prototype",

    patientProfile: "Alaye Alaisan",
    whoIsThisFor: "Tani ayẹwo yii jẹ fun?",
    age_child: "Ọmọ (0–12)",
    age_teen: "Ọdọ (13–17)",
    age_adult: "Agba (18–64)",
    age_elderly: "Agbalagba (65+)",
    back: "⬅ Pada",

    selectSymptom: "Yan Ẹka Aami Aisan",
    assessmentFor: "Ayẹwo fun",
    changeAge: "👤 Yi Ẹgbẹ Ọjọ-ori pada",
    searchPlaceholder: "🔎 Wa aami aisan (eyin, iba, eebi...)",
    noResults: "Ko si aami aisan to baamu. Gbiyanju: iba, eyin, inu, eebi.",
    symptom_fever: "🤒 Iba / Malaria",
    symptom_dental: "🦷 Irora Eyin",
    symptom_stomach: "🤢 Irora Inu",
    symptom_snakeBite: "🐍 Ìjẹ́ Ejò",

    snake_title: "Ayẹwo Ìjẹ́ Ejò",
    snake_q1: "Ṣé ejò ni o jẹ ọ tàbí o ro pé ejò ni?",
    notSure: "Mi ò dájú",
    urgent: "🔴 Pajawiri",
    snake_emergency: "Ìjẹ́ ejò jẹ pajawiri. Lọ sí ilé-iwosan lẹsẹkẹsẹ.",
    snake_do_title: "Ohun tí o yẹ kí o ṣe",
    snake_do_1: "Jẹ́ kí ibi tí ejò jẹ dúró ní ìdákẹ́jẹ.",
    snake_do_2: "Yọ ring tàbí aṣọ tí ó tight nitosi ibi tí ejò jẹ.",
    snake_do_3: "Lọ sí ilé-iwosan lẹsẹkẹsẹ.",
    snake_dont_title: "Má ṣe eleyi",
    snake_dont_1: "Má ge ọgbẹ náà.",
    snake_dont_2: "Má fa venom jade.",
    snake_dont_3: "Má fi nkan ipalara sí i.",

    feverTitle: "Ayẹwo Iba",
    feverQ1: "Ṣe iba ga pupọ, bii 39°C tabi ju bẹẹ lọ?",
    feverQ2Danger: "Ṣe awọn ami ewu wa, bii ailera pupọ, iruju, warapa, tabi iṣoro mimi?",
    feverQ2Days: "Ṣe iba ti ju ọjọ mẹta lọ?",

    dentalTitle: "Ayẹwo Irora Eyin",
    dentalQ1: "Ṣe irora naa lagbara?",
    dentalQ2: "Ṣe wiwu wa ni oju tabi gọ́mù?",

    stomachTitle: "Ayẹwo Irora Inu",
    stomachQ1: "Ṣe irora naa lagbara?",
    stomachQ2: "Ṣe o n eebi?",

    yes: "Bẹẹni",
    no: "Rara",

    resultTitle: "Abajade Ayẹwo",
    nextSteps: "Awọn igbesẹ to tẹle",
    redFlags: "Awọn ami ewu",
    generatedBy: "Generated by CareBridge Prototype",

    result_urgent_title: "🔴 Pajawiri",
    result_urgent_action: "Wa iranlọwọ ilera lẹsẹkẹsẹ.",
    result_moderate_title: "🟡 Alabọde",
    result_moderate_action: "Ṣọra gidigidi ki o ronu lati lọ si ile-iwosan laipẹ.",
    result_mild_title: "🟢 Rọrùn",
    result_mild_action: "Ó ṣeé ṣe kó rọrùn — sinmi ki o tọju ara rẹ.",

    aboutTitle: "Nipa CareBridge",
    aboutText1: "CareBridge jẹ àpẹẹrẹ triage aami aisan fẹẹrẹ ti a kọ fun awọn agbegbe ti asopọ intanẹẹti ko lagbara. Ó n ran awọn eniyan lọwọ lati mọ bi ipo ṣe le to.",
    aboutText2: "Eyi jẹ MVP prototype fun 3MTT NextGen Knowledge Showcase. Kì í ṣe irinṣẹ ìdánimọ àìsàn. Bí aami aisan bá buru, wá ìtọju amọja.",

    newAssessment: "Ayẹwo Tuntun",
    home: "Ile",
    ageNotePrefix: "Fun"
  },
  ha: {
    tagline: "Samfurin binciken alamu mai aiki ba tare da intanet ba",
    startCheck: "Fara Binciken Alamu",
    about: "Game da CareBridge",
    install: "Shigar da CareBridge",
    disclaimer: "⚠️ Wannan samfurin jagora ne kawai, ba kayan gano cuta ba. Idan alamar ta yi tsanani, a nemi kulawar kwararru.",
    footer: "Built for 3MTT NextGen Knowledge Showcase • MVP Prototype",

    patientProfile: "Bayanan Mara Lafiya",
    whoIsThisFor: "Wannan binciken na wa ne?",
    age_child: "Yaro (0–12)",
    age_teen: "Matashi (13–17)",
    age_adult: "Babba (18–64)",
    age_elderly: "Tsofaffi (65+)",
    back: "⬅ Baya",

    selectSymptom: "Zaɓi Nau'in Alama",
    assessmentFor: "Bincike don",
    changeAge: "👤 Canja Rukunin Shekaru",
    searchPlaceholder: "🔎 Nemi alama (hakori, zazzabi, amai...)",
    noResults: "Ba a sami alamar da ta dace ba. Gwada: zazzabi, hakori, ciki, amai.",
    symptom_fever: "🤒 Zazzabi / Malaria",
    symptom_dental: "🦷 Ciwon Hakori",
    symptom_stomach: "🤢 Ciwon Ciki",
    symptom_snakeBite: "🐍 Cizon Maciji",

    snake_title: "Binciken Cizon Maciji",
    snake_q1: "Shin maciji ne ya cije ka ko kana zargin maciji ne?",
    notSure: "Ban Tabbata Ba",
    urgent: "🔴 Gaggawa",
    snake_emergency: "Cizon maciji gaggawa ne. A je asibiti nan da nan.",
    snake_do_title: "Abin da za ka yi",
    snake_do_1: "Ka bar wurin da aka cije ba tare da motsi ba.",
    snake_do_2: "Cire zobe ko tufafi masu matsewa kusa da wurin.",
    snake_do_3: "Je asibiti nan da nan.",
    snake_dont_title: "Kada ka yi haka",
    snake_dont_1: "Kada ka yanke wurin.",
    snake_dont_2: "Kada ka tsotsa dafin.",
    snake_dont_3: "Kada ka shafa abubuwa masu cutarwa.",

    feverTitle: "Binciken Zazzabi",
    feverQ1: "Shin zazzabin ya yi yawa sosai, kamar 39°C ko fiye?",
    feverQ2Danger: "Akwai alamun haɗari kamar rauni mai tsanani, rikicewa, farfaɗiya, ko wahalar numfashi?",
    feverQ2Days: "Shin zazzabin ya wuce kwanaki uku?",

    dentalTitle: "Binciken Ciwon Hakori",
    dentalQ1: "Shin zafin ya yi tsanani?",
    dentalQ2: "Akwai kumburi a fuska ko gumi?",

    stomachTitle: "Binciken Ciwon Ciki",
    stomachQ1: "Shin ciwon ya yi tsanani?",
    stomachQ2: "Kana yin amai?",

    yes: "Eh",
    no: "A'a",

    resultTitle: "Sakamakon Bincike",
    nextSteps: "Matakai na gaba",
    redFlags: "Alamun haɗari",
    generatedBy: "Generated by CareBridge Prototype",

    result_urgent_title: "🔴 Gaggawa",
    result_urgent_action: "A nemi taimakon lafiya nan da nan.",
    result_moderate_title: "🟡 Matsakaici",
    result_moderate_action: "A kula sosai kuma a yi tunanin zuwa asibiti nan kusa.",
    result_mild_title: "🟢 Mai sauƙi",
    result_mild_action: "Wataƙila mai sauƙi ne — ka huta ka kula da kanka.",

    aboutTitle: "Game da CareBridge",
    aboutText1: "CareBridge samfurin triage ne mai sauƙi da aka gina domin wuraren da intanet ba ta ƙarfi. Yana taimakawa mutane su fahimci ko matsalar tana da sauƙi, matsakaici, ko gaggawa.",
    aboutText2: "Wannan MVP prototype ne na 3MTT NextGen Knowledge Showcase. Ba kayan gano cuta ba ne. Idan alama ta yi tsanani, a nemi ƙwararren kulawa.",

    newAssessment: "Sabon Bincike",
    home: "Gida",
    ageNotePrefix: "Don"
  },

  ig: {
    tagline: "Nlereanya nyocha mgbaàmà nke na-arụ ọrụ na-enweghị ịntanetị",
    startCheck: "Malite Nyocha Mgbaàmà",
    about: "Banyere CareBridge",
    install: "Wụnye CareBridge",
    disclaimer: "⚠️ Nke a bụ naanị nduzi enyemaka, ọ bụghị ngwaọrụ nyocha ọrịa. Ọ bụrụ na mgbaàmà sie ike, gaa hụ onye ọkachamara ahụike.",
    footer: "Built for 3MTT NextGen Knowledge Showcase • MVP Prototype",

    patientProfile: "Nkọwa Onye Ọrịa",
    whoIsThisFor: "Nyocha a bụ maka onye?",
    age_child: "Nwa (0–12)",
    age_teen: "Ntorobịa (13–17)",
    age_adult: "Okenye (18–64)",
    age_elderly: "Agadi (65+)",
    back: "⬅ Laghachi",

    selectSymptom: "Họrọ Ụdị Mgbaàmà",
    assessmentFor: "Nyocha maka",
    changeAge: "👤 Gbanwee Otu Afọ",
    searchPlaceholder: "🔎 Chọọ mgbaàmà (ezé, fever, vomiting...)",
    noResults: "Enweghị mgbaàmà dabara. Nwaa: fever, ezé, afo, vomiting.",
    symptom_fever: "🤒 Fever / Malaria",
    symptom_dental: "🦷 Mgbu Eze",
    symptom_stomach: "🤢 Mgbu Afo",
    symptom_snakeBite: "🐍 Iru Agwọ",

    snake_title: "Nyocha Iru Agwọ",
    snake_q1: "Agwọ ka tara gị ma ọ bụ i chere na ọ bụ agwọ?",
    notSure: "Amaghị M N'ezie",
    urgent: "🔴 Mberede",
    snake_emergency: "Iru agwọ bụ mberede. Gaa ụlọ ọgwụ ozugbo.",
    snake_do_title: "Ihe ị ga-eme ugbu a",
    snake_do_1: "Mee ka akụkụ ahụ a tara ghara ịkwaga.",
    snake_do_2: "Wepu mgbaaka ma ọ bụ uwe siri ike n'akụkụ ahụ a tara.",
    snake_do_3: "Gaa ụlọ ọgwụ ozugbo.",
    snake_dont_title: "Ekwela ime nke a",
    snake_dont_1: "Ekwela igbutu ọnya ahụ.",
    snake_dont_2: "Ekwela isụ venom ahụ.",
    snake_dont_3: "Ekwela itinye ihe ọ bụla na-emerụ ahụ.",

    feverTitle: "Nyocha Fever",
    feverQ1: "Fever ahụ dị oke elu, dịka 39°C ma ọ bụ karịa?",
    feverQ2Danger: "Enwere ihe ịrịba ama nke ihe egwu dịka adịghị ike nke ukwuu, mgbagwoju anya, ịma jijiji, ma ọ bụ nsogbu iku ume?",
    feverQ2Days: "Fever ahụ agafeela ụbọchị atọ?",

    dentalTitle: "Nyocha Mgbu Eze",
    dentalQ1: "Mgbu ahụ siri ike?",
    dentalQ2: "E nwere ọzịza n'ihu ma ọ bụ gọm?",

    stomachTitle: "Nyocha Mgbu Afo",
    stomachQ1: "Mgbu ahụ siri ike?",
    stomachQ2: "Ị na-awụfu ihe?",

    yes: "Ee",
    no: "Mba",

    resultTitle: "Nsonaazụ Nyocha",
    nextSteps: "Ihe ị ga-eme ọzọ",
    redFlags: "Ihe ịrịba ama ihe egwu",
    generatedBy: "Generated by CareBridge Prototype",

    result_urgent_title: "🔴 Mberede",
    result_urgent_action: "Chọọ enyemaka ahụike ozugbo.",
    result_moderate_title: "🟡 Nkezi",
    result_moderate_action: "Lezienụ ya anya nke ọma ma chee echiche ịga ụlọ ọgwụ n'oge na-adịghị anya.",
    result_mild_title: "🟢 Dị Mfe",
    result_mild_action: "O nwere ike ịbụ nke dị mfe — zuru ike ma lekọta onwe gị.",

    aboutTitle: "Banyere CareBridge",
    aboutText1: "CareBridge bụ nlele triage mgbaàmà dị mfe e wuru maka obodo ebe ịntanetị adịghị ike. Ọ na-enyere ndị mmadụ aka ịmata ma ọnọdụ ahụ dị mfe, nkezi, ma ọ bụ mberede.",
    aboutText2: "Nke a bụ MVP prototype maka 3MTT NextGen Knowledge Showcase. Ọ bụghị ngwaọrụ nyocha ọrịa. Ọ bụrụ na mgbaàmà sie ike, gaa hụ onye ọkachamara ahụike.",

    newAssessment: "Nyocha Ọzọ",
    home: "Ụlọ",
    ageNotePrefix: "Maka"
  }
};

function t(key){
  return (translations[currentLanguage] && translations[currentLanguage][key]) || translations.en[key] || key;
}

function updateStaticTexts(){
  const taglineText = document.getElementById("taglineText");
  const startBtn = document.getElementById("startBtn");
  const aboutBtn = document.getElementById("aboutBtn");
  const disclaimerText = document.getElementById("disclaimerText");
  const footerText = document.getElementById("footerText");
  const installBtn = document.getElementById("installBtn");

  if(taglineText) taglineText.textContent = t("tagline");
  if(startBtn) startBtn.textContent = t("startCheck");
  if(aboutBtn) aboutBtn.textContent = t("about");
  if(disclaimerText) disclaimerText.textContent = t("disclaimer");
  if(footerText) footerText.textContent = t("footer");
  if(installBtn) installBtn.textContent = t("install");

  document.querySelectorAll(".lang-btn").forEach(btn => btn.classList.remove("active"));
  const activeBtn = document.getElementById(`lang-${currentLanguage}`);
  if(activeBtn) activeBtn.classList.add("active");
}

function setLanguage(lang){
  currentLanguage = lang;
  localStorage.setItem("carebridgeLanguage", lang);
  updateStaticTexts();
  rerenderCurrentView();
}

function rerenderCurrentView(){
  switch(currentView.screen){
    case "age":
      selectAgeGroup();
      break;
    case "symptoms":
      showSymptomCategories();
      break;
    case "fever1":
      fever();
      break;
    case "fever2":
      feverStep2(currentView.data.highFever);
      break;
    case "dental1":
      dental();
      break;
    case "dental2":
      dentalStep2(currentView.data.severe);
      break;
    case "stomach1":
      stomach();
      break;
    case "stomach2":
      stomachStep2(currentView.data.severe);
      break;
    case "snake":
      snakeBite();
      break;
    case "result":
      showResult(currentView.data.level);
      break;
    case "about":
      showAbout();
      break;
    default:
      document.getElementById("app").innerHTML = "";
      currentView = { screen: "home" };
  }
}

document.addEventListener("DOMContentLoaded", () => {
  updateStaticTexts();
  updateInstallButton();
});

/* ===================== PWA INSTALL ===================== */

window.addEventListener("beforeinstallprompt", (e) => {
  e.preventDefault();
  deferredPrompt = e;
  updateInstallButton();
});

window.addEventListener("appinstalled", () => {
  deferredPrompt = null;
  updateInstallButton();
});

function updateInstallButton(){
  const installBtn = document.getElementById("installBtn");

  if(!installBtn) return;

  if(deferredPrompt){
    installBtn.style.display = "block";
    installBtn.onclick = installCareBridge;
  } else {
    installBtn.style.display = "none";
    installBtn.onclick = null;
  }
}

async function installCareBridge(){
  if(!deferredPrompt) return;

  deferredPrompt.prompt();
  await deferredPrompt.userChoice;
  deferredPrompt = null;
  updateInstallButton();
}

/* ===================== ENTRY ===================== */

function startCheck(){
  selectAgeGroup();
}

function selectAgeGroup(){
  currentView = { screen: "age" };

  document.getElementById("app").innerHTML = `
    <h2>${t("patientProfile")}</h2>
    <p>${t("whoIsThisFor")}</p>

    <div class="actions">
      <button onclick="setAgeGroup('child')">${t("age_child")}</button>
      <button onclick="setAgeGroup('teen')">${t("age_teen")}</button>
      <button onclick="setAgeGroup('adult')">${t("age_adult")}</button>
      <button onclick="setAgeGroup('elderly')">${t("age_elderly")}</button>
    </div>

    <div class="actions">
      <button onclick="goHome()">${t("back")}</button>
    </div>
  `;
}

function setAgeGroup(key){
  patientAgeGroup = { key };
  showSymptomCategories();
}

function showSymptomCategories(){
  currentView = { screen: "symptoms" };
  const ageLabel = patientAgeGroup ? t(`age_${patientAgeGroup.key}`) : "";

  document.getElementById("app").innerHTML = `
    <h2>${t("selectSymptom")}</h2>
    <p style="margin-top:6px; color:#475569; font-size:13px;">
      ${t("assessmentFor")}: <strong>${ageLabel}</strong>
    </p>

    <div class="actions" style="margin-top:10px; display:flex; gap:10px;">
      <button onclick="goHome()">${t("back")}</button>
      <button onclick="selectAgeGroup()">${t("changeAge")}</button>
    </div>

    <input
      id="searchSymptoms"
      placeholder="${t("searchPlaceholder")}"
      oninput="filterSymptoms()"
      style="margin:10px 0;"
    >

    <div id="noResults" style="display:none; font-size:13px; color:#64748b; margin:8px 0 4px 0;">
      ${t("noResults")}
    </div>

    <div class="actions" id="symptomList">
      <button onclick="fever()">${t("symptom_fever")}</button>
      <button onclick="dental()">${t("symptom_dental")}</button>
      <button onclick="stomach()">${t("symptom_stomach")}</button>
      <button onclick="snakeBite()">${t("symptom_snakeBite")}</button>
      <button onclick="cancerComingSoon()">${t("symptom_cancer")}</button>
    </div>
  `;
}

function filterSymptoms(){
  const input = document.getElementById("searchSymptoms").value.toLowerCase().trim();

  const symptomMap = [
    {
      id: 0,
      keywords: ["fever", "malaria", "temperature", "hot body", "hot", "chills", "sweating", "body hot", "zazzabi", "iba", "aru oku", "ọkụ", "oku"]
    },
    {
      id: 1,
      keywords: ["dental", "tooth", "teeth", "gum", "gums", "mouth", "swelling", "toothache", "tooth pain", "mouth pain", "hakori", "eyin", "eze"]
    },
    {
      id: 2,
      keywords: ["stomach", "belly", "vomit", "vomiting", "abdominal", "abdomen", "pain", "nausea", "stomach ache", "belly pain", "ciki", "inu", "afo"]
    },
    {
      id: 3,
      keywords: ["snake", "snake bite", "snakebite", "bite", "venom", "fang", "maciji", "ejo", "ejò", "agwo", "agwọ"]
    }
  ];

  const buttons = document.querySelectorAll("#symptomList button");
  let visibleCount = 0;

  buttons.forEach((button, index) => {
    const buttonText = button.innerText.toLowerCase();

    const matchedGroup = symptomMap.find(item => item.id === index);
    const matchesText = buttonText.includes(input);
    const matchesKeyword = matchedGroup
      ? matchedGroup.keywords.some(keyword => keyword.includes(input) || input.includes(keyword))
      : false;

    if(input === "" || matchesText || matchesKeyword){
      button.style.display = "block";
      visibleCount++;
    } else {
      button.style.display = "none";
    }
  });

  const noResults = document.getElementById("noResults");
  if(noResults){
    noResults.style.display = visibleCount === 0 ? "block" : "none";
  }
}

function renderQuestionScreen(title, question, yesAction, noAction, backAction){
  document.getElementById("app").innerHTML = `
    <h2>${title}</h2>
    <p>${question}</p>

    <div class="actions">
      <button onclick="${yesAction}">${t("yes")}</button>
      <button onclick="${noAction}">${t("no")}</button>
    </div>

    <div class="actions">
      <button onclick="${backAction}">${t("back")}</button>
    </div>
  `;
}

function newAssessment(){
  if(patientAgeGroup){
    showSymptomCategories();
  } else {
    selectAgeGroup();
  }
}

/* ===================== FEVER ===================== */

function fever(){
  currentView = { screen: "fever1" };
  renderQuestionScreen(
    t("feverTitle"),
    t("feverQ1"),
    "feverStep2(true)",
    "feverStep2(false)",
    "showSymptomCategories()"
  );
}

function feverStep2(highFever){
  currentView = { screen: "fever2", data: { highFever } };

  if(highFever){
    renderQuestionScreen(
      t("feverTitle"),
      t("feverQ2Danger"),
      "feverResult('dangerYes')",
      "feverResult('dangerNo')",
      "fever()"
    );
  } else {
    renderQuestionScreen(
      t("feverTitle"),
      t("feverQ2Days"),
      "feverResult('daysMore')",
      "feverResult('daysLess')",
      "fever()"
    );
  }
}

function feverResult(type){
  if(type === "dangerYes"){
    showResult("urgent");
  } else if(type === "dangerNo"){
    showResult("moderate");
  } else if(type === "daysMore"){
    showResult("urgent");
  } else {
    showResult("mild");
  }
}

/* ===================== DENTAL ===================== */

function dental(){
  currentView = { screen: "dental1" };
  renderQuestionScreen(
    t("dentalTitle"),
    t("dentalQ1"),
    "dentalStep2(true)",
    "dentalStep2(false)",
    "showSymptomCategories()"
  );
}

function dentalStep2(severe){
  currentView = { screen: "dental2", data: { severe } };
  renderQuestionScreen(
    t("dentalTitle"),
    t("dentalQ2"),
    `dentalResult(${severe}, true)`,
    `dentalResult(${severe}, false)`,
    "dental()"
  );
}

function dentalResult(severe, swelling){
  if(severe && swelling){
    showResult("urgent");
  } else if(severe || swelling){
    showResult("moderate");
  } else {
    showResult("mild");
  }
}

/* ===================== STOMACH ===================== */

function stomach(){
  currentView = { screen: "stomach1" };
  renderQuestionScreen(
    t("stomachTitle"),
    t("stomachQ1"),
    "stomachStep2(true)",
    "stomachStep2(false)",
    "showSymptomCategories()"
  );
}

function stomachStep2(severe){
  currentView = { screen: "stomach2", data: { severe } };
  renderQuestionScreen(
    t("stomachTitle"),
    t("stomachQ2"),
    `stomachResult(${severe}, true)`,
    `stomachResult(${severe}, false)`,
    "stomach()"
  );
}

function stomachResult(severe, vomiting){
  if(severe && vomiting){
    showResult("urgent");
  } else if(severe || vomiting){
    showResult("moderate");
  } else {
    showResult("mild");
  }
}

/* ===================== SNAKE BITE ===================== */

function snakeBite(){
  currentView = { screen: "snake" };

  document.getElementById("app").innerHTML = `
    <h2>${t("snake_title")}</h2>
    <p>${t("snake_q1")}</p>

    <div class="actions">
      <button onclick="snakeBiteResult()">${t("yes")}</button>
      <button onclick="snakeBiteResult()">${t("notSure")}</button>
      <button onclick="showSymptomCategories()">${t("no")}</button>
    </div>

    <div class="actions">
      <button onclick="showSymptomCategories()">${t("back")}</button>
    </div>
  `;
}

function snakeBiteResult(){
  document.getElementById("app").innerHTML = `
    <h2>${t("snake_title")}</h2>

    <div class="urgent" style="text-align:left;">
      <strong>${t("urgent")}</strong><br>
      ${t("snake_emergency")}
    </div>

    <div style="text-align:left; margin-top:12px;">
      <h3 style="margin:10px 0 6px 0; font-size:14px;">${t("snake_do_title")}</h3>
      <ul style="margin:0; padding-left:18px; line-height:1.5;">
        <li>${t("snake_do_1")}</li>
        <li>${t("snake_do_2")}</li>
        <li>${t("snake_do_3")}</li>
      </ul>

      <h3 style="margin:12px 0 6px 0; font-size:14px;">${t("snake_dont_title")}</h3>
      <ul style="margin:0; padding-left:18px; line-height:1.5;">
        <li>${t("snake_dont_1")}</li>
        <li>${t("snake_dont_2")}</li>
        <li>${t("snake_dont_3")}</li>
      </ul>
    </div>

    <p style="font-size:12px; color:#64748b; margin-top:10px;">
  ${t("generatedBy")} • ${new Date().toLocaleTimeString()}
</p>

    <div class="actions" style="margin-top:12px;">
      <button onclick="newAssessment()">${t("newAssessment")}</button>
      <button onclick="goHome()">${t("home")}</button>
    </div>
  `;
}

function cancerComingSoon(){
  document.getElementById("app").innerHTML = `
    <h2>${t("cancer_title")}</h2>

    <p class="coming-soon-text">${t("cancer_coming_soon")}</p>

    <div class="actions">
      <button onclick="showSymptomCategories()">${t("back")}</button>
    </div>
  `;
}

/* ===================== RESULT ===================== */

function getEnglishSteps(level){
  const data = {
    urgent: [
      "Go to the nearest hospital or clinic now.",
      "If you cannot move easily, ask someone to help you get care.",
      "Avoid self-medicating with unknown drugs."
    ],
    moderate: [
      "Rest and stay hydrated.",
      "Avoid triggers where relevant.",
      "If symptoms persist or worsen in 24 to 48 hours, visit a clinic."
    ],
    mild: [
      "Rest and hydrate.",
      "Use safe basic care where appropriate.",
      "If symptoms do not improve, reassess or visit a clinic."
    ]
  };
  return data[level];
}

function getEnglishRedFlags(level){
  const data = {
    urgent: [
      "Difficulty breathing",
      "Confusion or fainting",
      "Convulsions",
      "Severe swelling spreading",
      "Persistent vomiting or dehydration signs"
    ],
    moderate: [
      "Pain getting worse rapidly",
      "New swelling",
      "High fever developing",
      "Vomiting starts or increases"
    ],
    mild: [
      "Symptoms worsen instead of improving",
      "Severe pain starts",
      "Swelling appears",
      "High fever develops"
    ]
  };
  return data[level];
}

function showResult(level){
  currentView = { screen: "result", data: { level } };

  const title = t(`result_${level}_title`);
  const className = level;
  const action = t(`result_${level}_action`);
  const steps = getEnglishSteps(level);
  const redFlags = getEnglishRedFlags(level);

  const ageLabel = patientAgeGroup ? t(`age_${patientAgeGroup.key}`) : "Not set";
  const ageNote = `${t("ageNotePrefix")}: ${ageLabel}`;

  const stepsHtml = steps.map(step => `<li>${step}</li>`).join("");
  const flagsHtml = redFlags.map(flag => `<li>${flag}</li>`).join("");

  document.getElementById("app").innerHTML = `
    <h2>${t("resultTitle")}</h2>

    <div class="${className}" style="text-align:left;">
      <strong style="font-size:16px;">${title}</strong><br>
      <span>${action}</span>
      <div style="margin-top:6px; font-size:12px; opacity:0.95;">${ageNote}</div>
    </div>

    <div style="text-align:left; margin-top:12px;">
      <h3 style="margin:10px 0 6px 0; font-size:14px;">${t("nextSteps")}</h3>
      <ul style="margin:0; padding-left:18px; line-height:1.5;">
        ${stepsHtml}
      </ul>

      <h3 style="margin:12px 0 6px 0; font-size:14px;">${t("redFlags")}</h3>
      <ul style="margin:0; padding-left:18px; line-height:1.5;">
        ${flagsHtml}
      </ul>

      <p style="font-size:12px; color:#64748b; margin-top:10px;">
        ${t("generatedBy")} • ${new Date().toLocaleTimeString()}
      </p>
    </div>

    <div class="actions" style="margin-top:12px;">
      <button onclick="newAssessment()">${t("newAssessment")}</button>
      <button onclick="goHome()">${t("home")}</button>
    </div>
  `;
}

/* ===================== ABOUT + HOME ===================== */

function showAbout(){
  currentView = { screen: "about" };

  document.getElementById("app").innerHTML = `
    <h2>${t("aboutTitle")}</h2>
    <p>${t("aboutText1")}</p>
    <p>${t("aboutText2")}</p>

    <div class="actions">
      <button onclick="startCheck()">${t("startCheck")}</button>
    </div>
  `;
}

function goHome(){
  patientAgeGroup = null;
  currentView = { screen: "home" };
  document.getElementById("app").innerHTML = "";
}